# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gopalkamineni/Downloads/warehouse-robot-simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gopalkamineni/Downloads/warehouse-robot-simulator/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gopalkamineni/Downloads/warehouse-robot-simulator/build/CMakeFiles /Users/gopalkamineni/Downloads/warehouse-robot-simulator/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gopalkamineni/Downloads/warehouse-robot-simulator/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named warehouse_sim

# Build rule for target.
warehouse_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 warehouse_sim
.PHONY : warehouse_sim

# fast build rule for target.
warehouse_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/build
.PHONY : warehouse_sim/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pathfinder.o: src/pathfinder.cpp.o
.PHONY : src/pathfinder.o

# target to build an object file
src/pathfinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/pathfinder.cpp.o
.PHONY : src/pathfinder.cpp.o

src/pathfinder.i: src/pathfinder.cpp.i
.PHONY : src/pathfinder.i

# target to preprocess a source file
src/pathfinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/pathfinder.cpp.i
.PHONY : src/pathfinder.cpp.i

src/pathfinder.s: src/pathfinder.cpp.s
.PHONY : src/pathfinder.s

# target to generate assembly for a file
src/pathfinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/pathfinder.cpp.s
.PHONY : src/pathfinder.cpp.s

src/robot.o: src/robot.cpp.o
.PHONY : src/robot.o

# target to build an object file
src/robot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/robot.cpp.o
.PHONY : src/robot.cpp.o

src/robot.i: src/robot.cpp.i
.PHONY : src/robot.i

# target to preprocess a source file
src/robot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/robot.cpp.i
.PHONY : src/robot.cpp.i

src/robot.s: src/robot.cpp.s
.PHONY : src/robot.s

# target to generate assembly for a file
src/robot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/robot.cpp.s
.PHONY : src/robot.cpp.s

src/warehouse.o: src/warehouse.cpp.o
.PHONY : src/warehouse.o

# target to build an object file
src/warehouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/warehouse.cpp.o
.PHONY : src/warehouse.cpp.o

src/warehouse.i: src/warehouse.cpp.i
.PHONY : src/warehouse.i

# target to preprocess a source file
src/warehouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/warehouse.cpp.i
.PHONY : src/warehouse.cpp.i

src/warehouse.s: src/warehouse.cpp.s
.PHONY : src/warehouse.s

# target to generate assembly for a file
src/warehouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warehouse_sim.dir/build.make CMakeFiles/warehouse_sim.dir/src/warehouse.cpp.s
.PHONY : src/warehouse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... warehouse_sim"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pathfinder.o"
	@echo "... src/pathfinder.i"
	@echo "... src/pathfinder.s"
	@echo "... src/robot.o"
	@echo "... src/robot.i"
	@echo "... src/robot.s"
	@echo "... src/warehouse.o"
	@echo "... src/warehouse.i"
	@echo "... src/warehouse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

